### ISSUE TITLE
NumbaPerformanceWarning

### ISSUE THREAD

**Issue by ralphpeterson** [jackgoffinet/autoencoded-vocal-analysis#2]
Hello and thank you for AVA!

I recently did a fresh install of AVA on a new station and noticed a `numba` error during segmenting and visualization: `from numba.errors import NumbaPerformanceWarning`. It looks like in `numba 0.52.0` (the version I'm running) that `NumbaPerformanceWarning` is located in `numba.core.errors`. After changing that in the following scripts, things worked fine:

`ava/plotting/latent_projection.py`
`ava/segmenting/refine_segments.py`
`ava/data/data_container.py`

Don't know if this it the best way to solve this, but just a heads up if anyone runs into a similar issue!

**Comment by jackgoffinet** [comment]
Hi, thanks for pointing this out! It looks like I've been using Numba `0.44.1` and `0.45.1`. I just pushed a fix to the `dev` branch: [652e8b6](https://github.com/jackgoffinet/autoencoded-vocal-analysis/commit/652e8b6130bc26cfa05307bba57556d3e5481cd5)

The new import block looks like this:

```python
try: # Numba >= 0.52
	from numba.core.errors import NumbaPerformanceWarning
except ModuleNotFoundError:
	try: # Numba <= 0.45
		from numba.errors import NumbaPerformanceWarning
	except (NameError, ModuleNotFoundError):
		pass
```

I think this should work, but let me know if it doesn't for whatever reason.
