### ISSUE TITLE
Restating kernel ... (during refine_segments_pre_vae)

### ISSUE THREAD

**Issue by rnrpereira** [jackgoffinet/autoencoded-vocal-analysis#3]
Hi there,

First of all, congrats for the ava package contribution...
I started playing with the code a couple of days ago using rat usvs and was already able to create reasonable reconstructions (segmentation, preprocessing and training: using _mouse_sylls_mwe.py_ ). However, I decided to do a step by step analysis and got stuck with a crash during segmentation refinement. 

I am experiencing a _kernel restart_ during the last step of the _refine_segments_pre_vae method_ 
It happens while running the following line of code: 
`Parallel(n_jobs=n_jobs)(delayed(_update_segs_helper)(*args) for args in gen)`
_* (I know because I ran the method in a step-wise manner)_

There is no error message. Just:
`Restarting kernel...`

Then,
`In [1]:`
and a clean variable space....

Any ideas of what might be causing it?

Obs:
(1) Running inside Spyder 5.3.1/Python 3.8.13 64-bit | Qt 5.15.3 | PyQt5 5.15.4 | Linux 5.4.0-42-generic /Ubuntu 20.04.4 LTS
(2) In the _segs folder_ with .txt files (tab-delimited two-column of onsets and offsets), some are empty, as no usvs were detected.

Thanks, 
Rodrigo

**Comment by jackgoffinet** [comment]
Moved to the new AVA repo: https://github.com/pearsonlab/autoencoded-vocal-analysis/issues/2
